version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VERTEX_PROJECT=my-project
      - VERTEX_REGION=us-central1
      - VERTEX_INDEX_ENDPOINT=projects/123/locations/us-central1/indexEndpoints/456
      - VERTEX_DEPLOYED_INDEX_ID=0
      - MODALAB_DB_URL="postgresql://postgres:o%5B%25Fs%3AX1pv4m%40yC%3A@35.237.172.87:5432/postgres"

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
